### ISSUE TITLE
Feature Request: Zoom 

### ISSUE THREAD

**Issue by plutocrat** [initml/cleanup.pictures#10]
Great tool. I understand you probably want to keep it simple, but a zoom button allowing people to zoom in on a particular area and use finer brushes, would be a great addition. 

And maybe if you're doing that, then it would probably be best to separate the 'select' and 'remove' operations, so that the user could build up an area to remove in several stages, and then hit a 'Remove' button to actually do it. Selecting a complicated area in one go with a single brush, while keeping the mouse button depressed is hard.

**Comment by buddylee7** [comment]
Not sure of the "instant mode" could be done with the left mouse button and the "multiple strokes" could be done with the right mouse button...just a thought...
