### ISSUE TITLE
compression

### ISSUE THREAD

**Issue by Roki100** [initml/cleanup.pictures#9]
any possibility to disable the compression?
or is there other reason of big downscale?

**Comment by rahmanshaber** [comment]
Can't we run this in our own system so gpu memory is not an issue?

**Comment by Roki100** [comment]
> Can't we run this in our own system so gpu memory is not an issue? not server just regular windows linux system.

yeah that would be great

**Comment by cyrildiagne** [comment]
Yes that should definitely be possible! Running https://github.com/saic-mdal/lama locally and pointing the frontend directly to it. I don't think it requires a lot of changes on the code base and is mostly a matter of documentation.
But first, I'm adding HD/no-compression as a premium option (these servers are expensive 😅).

**Comment by Roki100** [comment]
> Yes that should definitely be possible! Running https://github.com/saic-mdal/lama locally and pointing the frontend directly to it. I don't think it requires a lot of changes on the code base and is mostly a matter of documentation.
> But first, I'm adding HD/no-compression as a premium option (these servers are expensive 😅).

it would be awesome to run it without compression locally out of the box (no code edits) in the future

**Comment by cyrildiagne** [comment]
Pushed an update that enables high resolution processed on our servers.
Please feel free to create a new issue specific to running cleanup locally to track it separately (this issue was about HD / compression).

**Comment by Sanster** [comment]
@Roki100 selfhost version: https://github.com/Sanster/lama-cleaner

**Comment by Roki100** [comment]
> @Roki100 selfhost version: https://github.com/Sanster/lama-cleaner

nice work ❤

**Comment by cyrildiagne** [comment]
@Sanster great work thanks! I've added it to the [README](https://github.com/initml/cleanup.pictures/blob/main/README.md)
